This notebook process staging dataset to targeted fact table.

In [1]:
import pandas as pd
import numpy as np
import yaml
from glob import glob
import os
from pathlib import Path
from datetime import date, timedelta, datetime
from pandas.tseries.holiday import USFederalHolidayCalendar
from pathlib import Path
import re
import hashlib

### Import staging dataset

In [2]:
df_dim = pd.read_csv("staging_ridership_output/dataset_metadata.csv")

In [3]:
df_dim.head()

,Unnamed: 0.1,Unnamed: 0,dataset_id,dataset_name,organization_name,service_name,start_date_collected,end_date_collected,reporting_unit,ridership_measure,...,stop_name_exists,stop_lat_exists,stop_lon_exists,boardings_exists,alightings_exists,ridership_exists,gtfs_url,gtfs_snapshot_date,gtfs_dataset_name,stop_coords_from_gtfs
0,0,0,189FC69D989010FD,golden_gate_park_shuttle_ridership,City and County of San Francisco,Golden Gate Park Shuttle,2024-07-01,2025-06-30,day,daily,...,1,0,0,0,0,1,https://api.511.org/transit/datafeeds?operator...,2026-02-04,Bay Area 511 Golden Gate Park Shuttle Schedule,1.0
1,1,1,957BBF3AD8FC1B44,samtrans_ridership,San Mateo County Transit District,SamTrans,2025-08-01,2025-08-31,day,daily,...,1,1,1,1,1,0,https://api.511.org/transit/datafeeds?operator...,2026-02-04,Bay Area 511 SamTrans Schedule,1.0
2,2,2,1B1BADA1E00153AF,sunline_transit_ridership,SunLine Transit Agency,SunLine Transit,2022-07-01,2025-06-30,fiscal_year,avg_daily,...,1,1,1,1,1,0,https://infopoint.sunline.org/InfoPoint/GTFS-Z...,2026-02-04,SunLine Avail Schedule,0.0
3,3,3,581003114DDAFDBE,santa_cruz_metro_ridership,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,2024-07-01,2025-06-30,fiscal_year,total,...,1,0,0,1,1,0,https://developer.scmetro.org/gtfs.zip,2026-02-04,Santa Cruz Schedule,1.0
4,4,4,1CCF9080DC015EB8,foothill_transit_ridership,Foothill Transit,Foothill Transit,2024-07-01,2025-06-30,day,daily,...,0,1,1,1,1,0,https://foothill3rdparty.rideralerts.com/mySto...,2026-02-04,Foothill Schedule,0.0

In [4]:
df_ridership = pd.read_csv("staging_ridership_output/staging_ridership_2026-02-11.csv", dtype={"stop_id": "string",
                                                                                                  "gtfs_stop_id": "string"})
df_ridership.head()

/tmp/ipykernel_278/199604141.py:1: DtypeWarning: Columns (4,5,6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ridership = pd.read_csv("staging_ridership_output/staging_ridership_2026-02-11.csv", dtype={"stop_id": "string",

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id
0,FF27A73278C43BCE,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,45.0,weekday,reported_daily,2024-07-01,2024-07-01,7602
1,31AC9C20F68713A9,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,59.0,weekday,reported_daily,2024-07-02,2024-07-02,7602
2,E021D40119E1054C,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,74.0,weekday,reported_daily,2024-07-03,2024-07-03,7602
3,B1F06206C22A5484,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,177.0,weekday,reported_daily,2024-07-04,2024-07-04,7602
4,5C7966570540D9F0,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,110.0,weekday,reported_daily,2024-07-05,2024-07-05,7602

In [5]:
# take stop id provided by agency by default, if no stop id provided, use gtfs stop id
df_ridership["stop_id_comb"] = df_ridership["stop_id"].combine_first(df_ridership["gtfs_stop_id"])

In [6]:
# df_ridership[df_ridership["stop_id_comb"].isna()]["organization_name"].unique()

**OmniTrans has stop names that are not matched in any stop name in GTFS.**

In [7]:
df_ridership[df_ridership["stop_id_comb"].isna()]

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id,stop_id_comb
1387166,77E94F017028B7F4,40F5F343F0BD5850,OmniTrans,OmniTrans,1,NaN,NaN,<NA>,2ND @ F ST,NaN,NaN,2.572603,0.619178,NaN,all,calculated_avg_daily,2023-07-01,2024-06-30,<NA>,<NA>
1387167,DE8C7BC2A243DAF0,40F5F343F0BD5850,OmniTrans,OmniTrans,1,NaN,NaN,<NA>,2ND @ G ST,NaN,NaN,1.410959,7.701370,NaN,all,calculated_avg_daily,2023-07-01,2024-06-30,<NA>,<NA>
1387189,D6159BD22F54DE4A,40F5F343F0BD5850,OmniTrans,OmniTrans,1,NaN,NaN,<NA>,EAST VALLEY,NaN,NaN,4.180822,3.473973,NaN,all,calculated_avg_daily,2023-07-01,2024-06-30,<NA>,<NA>
1387190,DED32295F9E7560B,40F5F343F0BD5850,OmniTrans,OmniTrans,1,NaN,NaN,<NA>,GILBERT @ KENWOOD,NaN,NaN,0.709589,1.536986,NaN,all,calculated_avg_daily,2023-07-01,2024-06-30,<NA>,<NA>
1387202,CAC937118E068294,40F5F343F0BD5850,OmniTrans,OmniTrans,1,NaN,NaN,<NA>,MT VERNON @ JOHNSON,NaN,NaN,5.550685,18.405479,NaN,all,calculated_avg_daily,2023-07-01,2024-06-30,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391988,7229C9A19DCA034E,40F5F343F0BD5850,OmniTrans,OmniTrans,215,NaN,NaN,<NA>,EAST VALLEY,NaN,NaN,0.520548,0.416438,NaN,all,calculated_avg_daily,2025-07-01,2026-06-30,<NA>,<NA>
1391990,5D8E6C4CABCFEFE2,40F5F343F0BD5850,OmniTrans,OmniTrans,215,NaN,NaN,<NA>,MT VERNON @ CENTREPOINTE,NaN,NaN,16.873973,17.495890,NaN,all,calculated_avg_daily,2025-07-01,2026-06-30,<NA>,<NA>
1391993,430BAE15C3322FC7,40F5F343F0BD5850,OmniTrans,OmniTrans,290,NaN,NaN,<NA>,ARROWHEAD MEDICAL CENTER,NaN,NaN,0.958904,0.843836,NaN,all,calculated_avg_daily,2025-07-01,2026-06-30,<NA>,<NA>
1391994,2FE4D5BD7C13CAD8,40F5F343F0BD5850,OmniTrans,OmniTrans,290,NaN,NaN,<NA>,EAST VALLEY,NaN,NaN,0.063014,0.057534,NaN,all,calculated_avg_daily,2025-07-01,2026-06-30,<NA>,<NA>
1391996,64B5D0078849B3E8,40F5F343F0BD5850,OmniTrans,OmniTrans,290,NaN,NaN,<NA>,Ontario Mills,NaN,NaN,1.287671,2.643836,NaN,all,calculated_avg_daily,2025-07-01,2026-06-30,<NA>,<NA>

### Handle OmniTrans Stop Name Format Inconsistency

In [8]:
omni_mask = df_ridership["organization_name"] == "OmniTrans"
t_df_omni = df_ridership.loc[omni_mask, ["stop_id_comb", "stop_name"]].copy()
t_df_omni["_orig_index"] = t_df_omni.index

In [9]:
street_types = ["street", "st", "avenue", "ave", "road", "rd", "boulevard", "blvd", "drive", "dr",
                "lane", "ln", "court", "ct", "place", "pl", "highway", "hwy", "way", "parkway", "pkwy"]

street_type_regex = r"\b(?:" + "|".join(street_types) + r")\b"

In [10]:
t_df_omni["stop_name_norm"] = t_df_omni["stop_name"].astype("string").str.lower().str.replace(r"\s+", " ", regex=True).str.strip()
# detect presence of any street type
t_df_omni["_has_street_type"] = t_df_omni["stop_name_norm"].str.contains(street_type_regex, regex=True, na=False)

t_df_omni["_stop_name_length"] = t_df_omni["stop_name_norm"].str.len()
# rank stop name variants within each stop id
canonical = t_df_omni.sort_values(by=["_has_street_type", "_stop_name_length"],
                                 ascending=[False, False]) \
                    .groupby("stop_id_comb", as_index=False).first()[["stop_id_comb", "stop_name"]].rename(columns={"stop_name": "canonical_stop_name"})
t_df_omni = t_df_omni.merge(canonical, on="stop_id_comb", how="left")
canonical.head()

  stop_id_comb       canonical_stop_name
0            1     ARROWHEAD REG MED CTR
1           10       Pacific High School
2          100  Foothill @ Riverside Ave
3          104      5th @ Medical Center
4          105       Merrill @ Riverside

In [11]:
df_ridership.loc[t_df_omni["_orig_index"], "stop_name"] = t_df_omni["canonical_stop_name"].values

### Agg to get avg daily ridership and make sure there is only one single row for one stop: 

- filter data for only most recent year/period
- recalculate avg daily for each stop across the most recent year/period

use stop_id_comb or gtfs_stop_id

#### For the reported daily ridership (or transaction level)
- first agg to stop level (if raw is trip-stop, or transaction)
- then take avg across the time span to get avg daily ridership

In [12]:
df_ridership.head()

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id,stop_id_comb
0,FF27A73278C43BCE,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,45.0,weekday,reported_daily,2024-07-01,2024-07-01,7602,7602
1,31AC9C20F68713A9,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,59.0,weekday,reported_daily,2024-07-02,2024-07-02,7602,7602
2,E021D40119E1054C,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,74.0,weekday,reported_daily,2024-07-03,2024-07-03,7602,7602
3,B1F06206C22A5484,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,177.0,weekday,reported_daily,2024-07-04,2024-07-04,7602,7602
4,5C7966570540D9F0,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,110.0,weekday,reported_daily,2024-07-05,2024-07-05,7602,7602

In [13]:
len(df_ridership["organization_name"].unique())

19

In [14]:
df_ridership["organization_name"].unique()

array(['City and County of San Francisco',
       'San Mateo County Transit District', 'SunLine Transit Agency',
       'Santa Cruz Metropolitan Transit District', 'Foothill Transit',
       'City of Fresno', 'San Diego Metropolitan Transit System',
       'Golden Gate Bridge, Highway and Transportation District',
       'San Francisco Bay Area Rapid Transit District',
       'City of Santa Monica', 'Long Beach Transit', 'OmniTrans',
       'Santa Barbara Metropolitan Transit District',
       'Gold Coast Transit District',
       'Sacramento Regional Transit District', 'City of Culver City',
       'Riverside Transit Agency',
       'Orange County Transportation Authority',
       'Peninsula Corridor Joint Powers Board'], dtype=object)

In [53]:
df_reported_daily = df_ridership[(df_ridership["daily_ridership_basis"] == "reported_daily") | 
                                 (df_ridership["organization_name"] == "Riverside Transit Agency")].copy()
df_reported_daily["organization_name"].unique()

array(['City and County of San Francisco',
       'San Mateo County Transit District', 'Foothill Transit',
       'City of Fresno',
       'Golden Gate Bridge, Highway and Transportation District',
       'San Francisco Bay Area Rapid Transit District',
       'Riverside Transit Agency',
       'Orange County Transportation Authority'], dtype=object)

In [54]:
len(df_reported_daily["organization_name"].unique())

8

In [55]:
df_reported_daily = df_reported_daily.groupby(["dataset_id", "organization_name", "service_name", "stop_id", "gtfs_stop_id", "stop_name",
                               "stop_lat", "stop_lon", "day_type", "daily_ridership_basis", "start_date", "end_date"], as_index=False, dropna=False) \
                    .agg(daily_total_ridership = ("daily_total_ridership", lambda x: x.sum(min_count=1)),
                         daily_alightings = ("daily_alightings", lambda x: x.sum(min_count=1)),
                         daily_boardings = ("daily_boardings", lambda x: x.sum(min_count=1))).reset_index()
df_reported_daily.head()

,index,dataset_id,organization_name,service_name,stop_id,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,daily_ridership_basis,start_date,end_date,daily_total_ridership,daily_alightings,daily_boardings
0,0,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-10-14,2024-10-14,NaN,3666.0,3735.0
1,1,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-11,2024-11-11,NaN,2301.0,2540.0
2,2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-28,2024-11-28,NaN,976.0,1021.0
3,3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-29,2024-11-29,NaN,1883.0,1971.0
4,4,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-12-24,2024-12-24,NaN,1931.0,1940.0

In [56]:
df_reported_daily["organization_name"].unique()

array(['San Francisco Bay Area Rapid Transit District',
       'City and County of San Francisco', 'Foothill Transit',
       'Orange County Transportation Authority',
       'Riverside Transit Agency', 'San Mateo County Transit District',
       'City of Fresno',
       'Golden Gate Bridge, Highway and Transportation District'],
      dtype=object)

In [57]:
len(df_reported_daily["organization_name"].unique())

8

In [58]:
# check if it is true that each stop has one record for each day (already checked all start date = end date)
df_reported_daily.groupby(["organization_name", "stop_id", "gtfs_stop_id", "stop_name", "start_date", "day_type"], as_index=False).size().sort_values(by="size", ascending=False).head(3)

,organization_name,stop_id,gtfs_stop_id,stop_name,start_date,day_type,size
0,City of Fresno,10,10,SHAW - CEDAR,2024-09-01,weekend,1
747317,Foothill Transit,2261,2261-a2,Huntington Dr and Rosemead Blvd E,2024-12-27,weekday,1
747323,Foothill Transit,2261,2261-a2,Huntington Dr and Rosemead Blvd E,2025-01-02,weekday,1

In [59]:
df_reported_daily_agg = df_reported_daily.groupby(by=["dataset_id", "organization_name", "service_name", "stop_id", "gtfs_stop_id", "stop_name", 
                                                    "stop_lat", "stop_lon", "day_type"], as_index=False, dropna=False).agg(avg_daily_boardings = ("daily_boardings", "mean"),
                                                                                                            avg_daily_alightings = ("daily_alightings", "mean"),
                                                                                                            avg_daily_ridership = ("daily_total_ridership", "mean"))
df_reported_daily_agg.head()

,dataset_id,organization_name,service_name,stop_id,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,avg_daily_boardings,avg_daily_alightings,avg_daily_ridership
0,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,holiday,2120.214286,2108.857143,NaN
1,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,saturday,2681.788462,2603.000000,NaN
2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,sunday,1817.115385,1814.557692,NaN
3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,weekday,5477.064777,5344.149798,NaN
4,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900209,19th Street / Oakland,37.808078,-122.268758,holiday,1979.714286,1905.000000,NaN

In [60]:
df_reported_daily_agg = pd.merge(df_reported_daily_agg, df_dim[["dataset_id", "start_date_collected", "end_date_collected"]], on="dataset_id")
df_reported_daily_agg.head()

,dataset_id,organization_name,service_name,stop_id,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,avg_daily_boardings,avg_daily_alightings,avg_daily_ridership,start_date_collected,end_date_collected
0,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,holiday,2120.214286,2108.857143,NaN,2024-10-01,2025-09-30
1,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,saturday,2681.788462,2603.000000,NaN,2024-10-01,2025-09-30
2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,sunday,1817.115385,1814.557692,NaN,2024-10-01,2025-09-30
3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900109,12th Street / Oakland City Center,37.803482,-122.271630,weekday,5477.064777,5344.149798,NaN,2024-10-01,2025-09-30
4,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,<NA>,900209,19th Street / Oakland,37.808078,-122.268758,holiday,1979.714286,1905.000000,NaN,2024-10-01,2025-09-30

In [62]:
len(df_reported_daily_agg["organization_name"].unique())

8

In [63]:
# check duplicates
t_dup_check = df_reported_daily_agg.groupby(["organization_name", "stop_id", "gtfs_stop_id", "stop_name", "day_type"], as_index=False).size().sort_values(by="size", ascending=False)
t_dup_check[t_dup_check["size"] > 1]

,organization_name,stop_id,gtfs_stop_id,stop_name,day_type,size
6845,Foothill Transit,2386,ps4-a2,San Gabriel Blvd and Sierra Madre Ave,holiday,2
9469,Foothill Transit,860,860-a1,Bonita Ave and Cataract Ave W,weekday,2
7002,Foothill Transit,2495,2495-a2,Sunset Ave and Amar Rd S,weekday,2
9466,Foothill Transit,859,859-a1,Bonita Ave and Cataract Ave E,weekday,2
9467,Foothill Transit,859,859-a1,Bonita Ave and Cataract Ave E,weekend,2
6005,Foothill Transit,177,ps1-a2,Azusa Intermodal Transit Center,weekday,2
6004,Foothill Transit,177,ps1-a2,Azusa Intermodal Transit Center,holiday,2
9468,Foothill Transit,860,860-a1,Bonita Ave and Cataract Ave W,holiday,2
6006,Foothill Transit,177,ps1-a2,Azusa Intermodal Transit Center,weekend,2
9470,Foothill Transit,860,860-a1,Bonita Ave and Cataract Ave W,weekend,2
7003,Foothill Transit,2495,2495-a2,Sunset Ave and Amar Rd S,weekend,2
6847,Foothill Transit,2386,ps4-a2,San Gabriel Blvd and Sierra Madre Ave,weekend,2
6846,Foothill Transit,2386,ps4-a2,San Gabriel Blvd and Sierra Madre Ave,weekday,2

In [39]:
df_reported_daily_agg[(df_reported_daily_agg["organization_name"] == "Foothill Transit") &
                      (df_reported_daily_agg["stop_id"] == "2386") & 
                      (df_reported_daily_agg["day_type"] == "weekday")]

,dataset_id,organization_name,service_name,stop_id,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,avg_daily_boardings,avg_daily_alightings,avg_daily_ridership,start_date_collected,end_date_collected
2146,1CCF9080DC015EB8,Foothill Transit,Foothill Transit,2386,ps4-a2,San Gabriel Blvd and Sierra Madre Ave,34.146327,-117.908993,weekday,19.597561,8.707317,NaN,2024-07-01,2025-06-30
2149,1CCF9080DC015EB8,Foothill Transit,Foothill Transit,2386,ps4-a2,San Gabriel Blvd and Sierra Madre Ave,34.146336,-117.908951,weekday,21.856287,7.682635,NaN,2024-07-01,2025-06-30

#### For the reported avg ridership

In [64]:
df_reported_avg = df_ridership[(df_ridership["daily_ridership_basis"] == "reported_avg_daily")].copy()
df_reported_avg["organization_name"].unique()

array(['SunLine Transit Agency', 'San Diego Metropolitan Transit System',
       'City of Santa Monica', 'Long Beach Transit',
       'Gold Coast Transit District',
       'Sacramento Regional Transit District', 'City of Culver City',
       'Peninsula Corridor Joint Powers Board'], dtype=object)

In [65]:
len(df_reported_avg["organization_name"].unique())

8

#### SunLine, SDMTS, Long Beach Transit, provided avg daily for each year/fiscal year
#### Gold Coast Transit District, raw is avg for the given month (only one month worth of data)
#### SacRT raw is avg for given period (Sep-Dec 2023)

#### Santa Monica

raw data is avg for every 4 months from 2024-08-01 to 2025-11-30, 4 periods in total.

In [73]:
df_reported_avg[(df_reported_avg["organization_name"] == "City of Santa Monica")]["start_date"].unique()

array(['2024-08-01', '2024-12-01', '2025-04-01', '2025-08-01'],
      dtype=object)

In [76]:
df_reported_avg[(df_reported_avg["organization_name"] == "City of Santa Monica")].head()

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id,stop_id_comb
1366782,A804D30789A774D2,395857DB9F379E73,City of Santa Monica,Big Blue Bus,1,Main St & Santa Monica Blvd/UCLA,EASTBOUND,-4.0,MAIN NB/WESTMINSTER FS,33.990316,-118.472653,28.909881,0.111111,NaN,saturday,reported_avg_daily,2024-08-01,2024-11-30,346,-4.0
1366783,FDA60BBC003F98D9,395857DB9F379E73,City of Santa Monica,Big Blue Bus,1,Main St & Santa Monica Blvd/UCLA,EASTBOUND,1000.0,4TH NB/COLORADO FS (Downtown SM Station),34.014235,-118.492457,116.886196,187.964533,NaN,saturday,reported_avg_daily,2024-08-01,2024-11-30,21,1000.0
1366784,8A48393FDA926F9C,395857DB9F379E73,City of Santa Monica,Big Blue Bus,1,Main St & Santa Monica Blvd/UCLA,EASTBOUND,1054.0,4TH NB/PICO FS,34.010034,-118.487580,26.176476,41.298676,NaN,saturday,reported_avg_daily,2024-08-01,2024-11-30,284,1054.0
1366785,0BF5B3C802D0F7CB,395857DB9F379E73,City of Santa Monica,Big Blue Bus,1,Main St & Santa Monica Blvd/UCLA,EASTBOUND,1218.0,MAIN NB/HILL NS,34.000950,-118.482391,36.858219,4.749936,NaN,saturday,reported_avg_daily,2024-08-01,2024-11-30,340,1218.0
1366786,684FA140C497473F,395857DB9F379E73,City of Santa Monica,Big Blue Bus,1,Main St & Santa Monica Blvd/UCLA,EASTBOUND,1221.0,MAIN NB/MARINE NS,33.997991,-118.479444,73.455075,9.204640,NaN,saturday,reported_avg_daily,2024-08-01,2024-11-30,202,1221.0

#### Caltrain

raw data is avg for each month, from 2023-11-01 to 2025-07-01

In [77]:
df_reported_avg[(df_reported_avg["organization_name"] == "Peninsula Corridor Joint Powers Board")]["start_date"].unique()

array(['2025-07-01', '2025-06-01', '2025-05-01', '2025-04-01',
       '2025-03-01', '2025-02-01', '2025-01-01', '2024-12-01',
       '2024-11-01', '2024-10-01', '2024-09-01', '2024-08-01',
       '2024-07-01', '2024-06-01', '2024-05-01', '2024-04-01',
       '2024-03-01', '2024-02-01', '2024-01-01', '2023-12-01',
       '2023-11-01'], dtype=object)

For these agencies, just agg over routes and directions, no need to take avg again.

In [79]:
df_reported_avg_agg = df_reported_avg.groupby(["dataset_id", "organization_name", "service_name", "stop_id", "gtfs_stop_id", "stop_name",
                               "stop_lat", "stop_lon", "day_type", "daily_ridership_basis", "start_date", "end_date"], as_index=False, dropna=False) \
                    .agg(daily_total_ridership = ("daily_total_ridership", lambda x: x.sum(min_count=1)),
                         daily_alightings = ("daily_alightings", lambda x: x.sum(min_count=1)),
                         daily_boardings = ("daily_boardings", lambda x: x.sum(min_count=1))).reset_index()

In [80]:
df_reported_avg_agg.head()

,index,dataset_id,organization_name,service_name,stop_id,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,daily_ridership_basis,start_date,end_date,daily_total_ridership,daily_alightings,daily_boardings
0,0,1B1BADA1E00153AF,SunLine Transit Agency,SunLine Transit,1,1,Palm@2Bunch,33.947457,-116.501166,NaN,reported_avg_daily,2022-07-01,2023-06-30,NaN,32.12,23.47
1,1,1B1BADA1E00153AF,SunLine Transit Agency,SunLine Transit,1,1,Palm@2Bunch,33.947457,-116.501166,NaN,reported_avg_daily,2023-07-01,2024-06-30,NaN,29.00,25.90
2,2,1B1BADA1E00153AF,SunLine Transit Agency,SunLine Transit,1,1,Palm@2Bunch,33.947457,-116.501166,NaN,reported_avg_daily,2024-07-01,2025-06-30,NaN,24.73,21.05
3,3,1B1BADA1E00153AF,SunLine Transit Agency,SunLine Transit,1,1,Palm@2Bunch,33.947457,-116.501166,NaN,reported_avg_daily,2025-03-01,2025-05-31,NaN,20.28,15.59
4,4,1B1BADA1E00153AF,SunLine Transit Agency,SunLine Transit,10,10,PalmCyn@Escuela,33.848167,-116.547967,NaN,reported_avg_daily,2022-07-01,2023-06-30,NaN,1.08,1.62

In [81]:
len(df_reported_avg_agg["organization_name"].unique())

8

#### For calculated_avg

- Santa Cruz Metro: raw is total for one fiscal year (2024-07-01 to 2025-06-30)
- OmniTrans: raw is total for each fiscal year from 2024-2026
- SBMTD: raw is monthly total for each month from 2024-11-01 to 2025-10-31

In [82]:
df_calc_avg = df_ridership[(df_ridership["daily_ridership_basis"] == "calculated_avg_daily")].copy()
df_calc_avg["organization_name"].unique()

array(['Santa Cruz Metropolitan Transit District', 'OmniTrans',
       'Santa Barbara Metropolitan Transit District'], dtype=object)

In [83]:
len(df_calc_avg)

13194

In [84]:
df_calc_avg.head()

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id,stop_id_comb
68671,48910BC0E7DA0DB4,581003114DDAFDBE,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,NaN,NaN,NaN,2170,17th Ave + Brommer,36.970665,-121.984764,0.887671,2.358904,NaN,all,calculated_avg_daily,2024-07-01,2025-06-30,1394,2170
68672,9F8FE6A2CB9CC34C,581003114DDAFDBE,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,NaN,NaN,NaN,2171,17th Ave + Felt,36.967159,-121.985489,3.438356,5.123288,NaN,all,calculated_avg_daily,2024-07-01,2025-06-30,1395,2171
68673,33C933A9C1B16916,581003114DDAFDBE,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,NaN,NaN,NaN,2175,17th Ave + Felt,36.967182,-121.985222,6.879452,2.336986,NaN,all,calculated_avg_daily,2024-07-01,2025-06-30,1399,2175
68674,5317D6FF25FDE70E,581003114DDAFDBE,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,NaN,NaN,NaN,2178,17th Ave + Kinsley,36.969753,-121.984810,3.293151,1.484932,NaN,all,calculated_avg_daily,2024-07-01,2025-06-30,1401,2178
68675,53E9394613D4D486,581003114DDAFDBE,Santa Cruz Metropolitan Transit District,Santa Cruz METRO,NaN,NaN,NaN,2173,17th Ave + Matthews Ln,36.963676,-121.987267,4.076712,3.400000,NaN,all,calculated_avg_daily,2024-07-01,2025-06-30,1397,2173

In [12]:
df_agg = df_ridership.groupby(["dataset_id", "organization_name", "service_name", "stop_id", "gtfs_stop_id", "stop_name",
                               "stop_lat", "stop_lon", "day_type", "daily_ridership_basis", "start_date", "end_date"], as_index=False, dropna=False) \
                    .agg(daily_total_ridership = ("daily_total_ridership", lambda x: x.sum(min_count=1)),
                         daily_alightings = ("daily_alightings", lambda x: x.sum(min_count=1)),
                         daily_boardings = ("daily_boardings", lambda x: x.sum(min_count=1))).reset_index()

# drop index col
df_agg.drop(columns="index", inplace=True)

df_agg.head()

,dataset_id,organization_name,service_name,gtfs_stop_id,stop_name,stop_lat,stop_lon,day_type,daily_ridership_basis,start_date,end_date,daily_total_ridership,daily_alightings,daily_boardings
0,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-10-14,2024-10-14,NaN,3666.0,3735.0
1,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-11,2024-11-11,NaN,2301.0,2540.0
2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-28,2024-11-28,NaN,976.0,1021.0
3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-11-29,2024-11-29,NaN,1883.0,1971.0
4,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,holiday,reported_daily,2024-12-24,2024-12-24,NaN,1931.0,1940.0

In [13]:
t_df = df_agg.groupby(["dataset_id", "organization_name", "service_name", "gtfs_stop_id", "stop_name", "day_type", "start_date", "end_date"]).size().reset_index(name="row_count").sort_values(by="row_count", ascending=False)
t_df.head(10)

,dataset_id,organization_name,service_name,gtfs_stop_id,stop_name,day_type,start_date,end_date,row_count
0,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,holiday,2024-10-14,2024-10-14,1
789802,9B106785FD780293,City of Fresno,Fresno Area Express,1544,NW 3965 JENSEN,weekend,2025-04-20,2025-04-20,1
789854,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,weekday,2024-09-09,2024-09-09,1
789853,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,weekday,2024-09-06,2024-09-06,1
789852,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,weekday,2024-09-05,2024-09-05,1
789851,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,weekday,2024-09-04,2024-09-04,1
789850,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,weekday,2024-09-03,2024-09-03,1
789849,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,holiday,2025-07-04,2025-07-04,1
789848,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,holiday,2025-06-19,2025-06-19,1
789847,9B106785FD780293,City of Fresno,Fresno Area Express,1545,NW PULLMAN - JENSEN,holiday,2025-05-26,2025-05-26,1

In [14]:
t_df[t_df["row_count"] > 1]["organization_name"].unique()

array([], dtype=object)

In [15]:
t_df[t_df["row_count"] > 1].groupby(by=["organization_name", "service_name", "day_type", "start_date", "end_date"])["gtfs_stop_id"].nunique().reset_index()

Empty DataFrame
Columns: [organization_name, service_name, day_type, start_date, end_date, gtfs_stop_id]
Index: []

**Note: The duplicates in SamTrans is the stop id that is not in GTFS - and in ridership data, a stop id can have more than one pair of lat/lon. Looks like it is vehicle position. So we use GTFS lat/lon mapped in using stop id for the aggregation.**

In [18]:
org_name = "City and County of San Francisco"
df_org = df_ridership[df_ridership["organization_name"] == org_name]
df_org.head()

,record_id,dataset_id,organization_name,service_name,route_id,route_name,direction,stop_id,stop_name,stop_lat,stop_lon,daily_boardings,daily_alightings,daily_total_ridership,day_type,daily_ridership_basis,start_date,end_date,gtfs_stop_id,stop_id_comb
0,FF27A73278C43BCE,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,45.0,weekday,reported_daily,2024-07-01,2024-07-01,7602,7602
1,31AC9C20F68713A9,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,59.0,weekday,reported_daily,2024-07-02,2024-07-02,7602,7602
2,E021D40119E1054C,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,74.0,weekday,reported_daily,2024-07-03,2024-07-03,7602,7602
3,B1F06206C22A5484,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,177.0,weekday,reported_daily,2024-07-04,2024-07-04,7602,7602
4,5C7966570540D9F0,189FC69D989010FD,City and County of San Francisco,Golden Gate Park Shuttle,NaN,NaN,NaN,<NA>,Blue Heron Boathouse,37.77084,-122.476829,NaN,NaN,110.0,weekday,reported_daily,2024-07-05,2024-07-05,7602,7602

In [ ]:
df_org_res = df_org.groupby(["dataset_id", "organization_name", "service_name", "gtfs_stop_id", 
                             "stop_id", "stop_name", "stop_lat", "stop_lon"], as_index=False).agg()

#### Add key

In [24]:
def generate_key(*args, len=16, sep="|"):
    """Generate short reproducible hash ID based on input string"""
    key = sep.join(str(arg) for arg in args if arg is not None).encode("utf-8")
    return hashlib.sha1(key).hexdigest()[:len].upper()

In [25]:
df_agg = df_agg.rename(columns={"gtfs_stop_id": "stop_id"})

In [26]:
df_agg["record_id"] = df_agg.apply(lambda row: generate_key(row["organization_name"],
                                                           row["service_name"],
                                                           row["stop_id"],
                                                           row["stop_name"],
                                                           row["day_type"],
                                                           row["start_date"]
                                                          ), axis=1, result_type="expand")

In [27]:
# check duplicates
t_df_agg = df_agg.groupby("record_id").size().reset_index(name="count")
t_df_agg[t_df_agg["count"] > 1]

Empty DataFrame
Columns: [record_id, count]
Index: []

In [28]:
df_agg = df_agg[["record_id", "dataset_id", "organization_name", "service_name", "stop_id", "stop_name", "stop_lat", "stop_lon", 
                 "daily_alightings", "daily_boardings", "daily_total_ridership", "start_date", "end_date", "daily_ridership_basis", "day_type"]]

#### Export

In [29]:
today = date.today().strftime("%Y-%m-%d")
df_agg.to_csv(f"fact_ridership_output/fct_ridership_{today}.csv", index=False) # save a copy

In [30]:
df_agg.head()

,record_id,dataset_id,organization_name,service_name,stop_id,stop_name,stop_lat,stop_lon,daily_alightings,daily_boardings,daily_total_ridership,start_date,end_date,daily_ridership_basis,day_type
0,947E32A15D31E288,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,3666.0,3735.0,NaN,2024-10-14,2024-10-14,reported_daily,holiday
1,50A204C99EF493D2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,2301.0,2540.0,NaN,2024-11-11,2024-11-11,reported_daily,holiday
2,A6B375D418BC5853,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,976.0,1021.0,NaN,2024-11-28,2024-11-28,reported_daily,holiday
3,0A853373D96249B8,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,1883.0,1971.0,NaN,2024-11-29,2024-11-29,reported_daily,holiday
4,6D6FA33361F1AFA3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,1931.0,1940.0,NaN,2024-12-24,2024-12-24,reported_daily,holiday

In [2]:
t_df = pd.read_csv("fact_ridership_output/fct_ridership_2026-02-11.csv")
t_df.head()

/tmp/ipykernel_669/1237863935.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  t_df = pd.read_csv("fact_ridership_output/fct_ridership_2026-02-11.csv")

,record_id,dataset_id,organization_name,service_name,stop_id,stop_name,stop_lat,stop_lon,daily_alightings,daily_boardings,daily_total_ridership,start_date,end_date,daily_ridership_basis,day_type
0,947E32A15D31E288,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,3666.0,3735.0,NaN,2024-10-14,2024-10-14,reported_daily,holiday
1,50A204C99EF493D2,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,2301.0,2540.0,NaN,2024-11-11,2024-11-11,reported_daily,holiday
2,A6B375D418BC5853,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,976.0,1021.0,NaN,2024-11-28,2024-11-28,reported_daily,holiday
3,0A853373D96249B8,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,1883.0,1971.0,NaN,2024-11-29,2024-11-29,reported_daily,holiday
4,6D6FA33361F1AFA3,011CF30F49575609,San Francisco Bay Area Rapid Transit District,Bay Area Rapid Transit,900109,12th Street / Oakland City Center,37.803482,-122.27163,1931.0,1940.0,NaN,2024-12-24,2024-12-24,reported_daily,holiday

In [5]:
t_df["organization_name"].unique().tolist()

['San Francisco Bay Area Rapid Transit District',
 'Santa Barbara Metropolitan Transit District',
 'City and County of San Francisco',
 'Foothill Transit',
 'Sacramento Regional Transit District',
 'Orange County Transportation Authority',
 'City of Culver City',
 'City of Santa Monica',
 'Long Beach Transit',
 'OmniTrans',
 'Santa Cruz Metropolitan Transit District',
 'San Diego Metropolitan Transit System',
 'San Mateo County Transit District',
 'City of Fresno',
 'Gold Coast Transit District',
 'Peninsula Corridor Joint Powers Board',
 'Golden Gate Bridge, Highway and Transportation District']

In [10]:
t_df.groupby(["organization_name", "daily_ridership_basis"], as_index=False).agg(min_date = ("start_date", "min"),
                                                                                 max_date = ("end_date", "max"))

,organization_name,daily_ridership_basis,min_date,max_date
0,City and County of San Francisco,reported_daily,2024-07-01,2025-06-30
1,City of Culver City,reported_avg_daily,2025-07-14,2025-08-25
2,City of Fresno,reported_daily,2024-09-01,2025-08-31
3,City of Santa Monica,reported_avg_daily,2024-08-01,2025-11-30
4,Foothill Transit,reported_daily,2024-07-01,2025-06-30
5,Gold Coast Transit District,reported_avg_daily,2025-05-01,2025-05-31
6,"Golden Gate Bridge, Highway and Transportation...",reported_daily,2025-09-01,2025-09-30
7,Long Beach Transit,reported_avg_daily,2024-07-01,2025-06-30
8,OmniTrans,calculated_avg_daily,2023-07-01,2026-06-30
9,Orange County Transportation Authority,reported_daily,2025-02-04,2025-02-04
10,Peninsula Corridor Joint Powers Board,reported_avg_daily,2023-11-01,2025-07-31
11,Sacramento Regional Transit District,reported_avg_daily,2023-09-01,2023-12-31
12,San Diego Metropolitan Transit System,reported_avg_daily,2024-09-01,2025-01-25
13,San Francisco Bay Area Rapid Transit District,reported_daily,2024-10-01,2025-09-30
14,San Mateo County Transit District,reported_daily,2025-08-01,2025-08-31
15,Santa Barbara Metropolitan Transit District,calculated_avg_daily,2024-11-01,2025-10-31
16,Santa Cruz Metropolitan Transit District,calculated_avg_daily,2024-07-01,2025-06-30

In [7]:
t_df[t_df["daily_ridership_basis"] == "calculated_avg_daily"]["organization_name"].unique()

array(['Santa Barbara Metropolitan Transit District', 'OmniTrans',
       'Santa Cruz Metropolitan Transit District'], dtype=object)