In [1]:
import geopandas as gpd
import gcsfs
import pandas as pd

from google.cloud import bigquery

from shared_vars import RAW_GCS, INTERMED_GCS, AGENCY_TO_GTFS_NAME_DICT, RAW_DATA_YAML
from ridership_utils import bq_utils, utils

In [2]:
SCHEDULE_FEEDS_FILENAME = "schedule_feeds"

feeds_df = pd.read_parquet(
    f"{INTERMED_GCS}{SCHEDULE_FEEDS_FILENAME}.parquet",
    filesystem = gcsfs.GCSFileSystem()
)

In [3]:
test_operator = "Bay Area 511 BART Schedule"

In [4]:
feeds_df[feeds_df.schedule_name==test_operator].head(2)

,feed_key,schedule_name,service_date_start,service_date_end
3810,3d1e24aeee75adb17662d9d8cb2ec350,Bay Area 511 BART Schedule,2026-05-28,2026-05-28
3811,bfb2078783000a9e17d3bdeb0a281f4f,Bay Area 511 BART Schedule,2026-04-24,2026-05-27

In [5]:
list_of_operators = list(RAW_DATA_YAML.keys())

operators_with_ridership = pd.concat([
    pd.read_parquet(
        f"{RAW_GCS}{agency_name}/ridership_round1.parquet",
        columns = ["schedule_name", "start_date", "end_date"],
        filesystem = gcsfs.GCSFileSystem()
    ) for agency_name in list_of_operators
    ], axis=0, ignore_index=True
).drop_duplicates().reset_index(drop=True)

ridership_start = operators_with_ridership[
    operators_with_ridership.schedule_name==test_operator
].start_date.min()

ridership_end = operators_with_ridership[
    operators_with_ridership.schedule_name==test_operator
].end_date.max()

In [6]:
ridership_start, ridership_end

(Timestamp('2024-10-01 00:00:00'), Timestamp('2025-09-30 00:00:00'))

In [7]:
test_feeds_df = feeds_df[
    (feeds_df.schedule_name==test_operator) 
].sort_values(
    ["service_date_start", "service_date_end"]
).reset_index(drop=True)

test_feeds_df

,feed_key,schedule_name,service_date_start,service_date_end
0,d80a42d70891b7549640562e5be47757,Bay Area 511 BART Schedule,2023-01-01,2023-01-11
1,73cdc9157518a7ee1a30809d40a3858a,Bay Area 511 BART Schedule,2023-01-12,2023-01-25
2,59b6a595ab2fea442b8000cd97f372bc,Bay Area 511 BART Schedule,2023-01-26,2023-02-13
3,cacb113abcfffee16b7ffd0fc3be77b0,Bay Area 511 BART Schedule,2023-02-14,2023-03-01
4,3e1d39f4d0919bc8aca8d5f99bfea726,Bay Area 511 BART Schedule,2023-03-02,2023-03-02
...,...,...,...,...
72,b4dda97100acf38a587f7f0fb447f6a9,Bay Area 511 BART Schedule,2026-01-01,2026-01-02
73,4d1c677d47f3c48a4323f506927383d3,Bay Area 511 BART Schedule,2026-01-03,2026-03-31
74,1aa4230f065e18b82c78ae8b0aabaf19,Bay Area 511 BART Schedule,2026-04-01,2026-04-23
75,bfb2078783000a9e17d3bdeb0a281f4f,Bay Area 511 BART Schedule,2026-04-24,2026-05-27
76,3d1e24aeee75adb17662d9d8cb2ec350,Bay Area 511 BART Schedule,2026-05-28,2026-05-28

In [8]:
# this condition is grabbing way too much still
test_feeds_df[
    (
        (test_feeds_df.service_date_start <= ridership_start) &
        (test_feeds_df.service_date_end <= ridership_end)
    ) | 
    (
        (test_feeds_df.service_date_end >= ridership_end) &
        (test_feeds_df.service_date_start >= ridership_start)
    )
]

,feed_key,schedule_name,service_date_start,service_date_end
0,d80a42d70891b7549640562e5be47757,Bay Area 511 BART Schedule,2023-01-01,2023-01-11
1,73cdc9157518a7ee1a30809d40a3858a,Bay Area 511 BART Schedule,2023-01-12,2023-01-25
2,59b6a595ab2fea442b8000cd97f372bc,Bay Area 511 BART Schedule,2023-01-26,2023-02-13
3,cacb113abcfffee16b7ffd0fc3be77b0,Bay Area 511 BART Schedule,2023-02-14,2023-03-01
4,3e1d39f4d0919bc8aca8d5f99bfea726,Bay Area 511 BART Schedule,2023-03-02,2023-03-02
5,66b32bcbcd47ced39f98c648b038914c,Bay Area 511 BART Schedule,2023-03-03,2023-03-10
6,2083403c90fd9bd77ccb235906093136,Bay Area 511 BART Schedule,2023-03-11,2023-03-17
7,7cf2ecc1c5ff968d5acaacec0814c1c9,Bay Area 511 BART Schedule,2023-03-18,2023-03-31
8,19ce0483d15fbbec6aa8b9e27883c95e,Bay Area 511 BART Schedule,2023-04-01,2023-05-04
9,23b6c8cb61db6a290b4d554f36fe7d0f,Bay Area 511 BART Schedule,2023-05-05,2023-05-16
10,e7a095d6462b4dc34afdbb6b8fda2974,Bay Area 511 BART Schedule,2023-05-17,2023-05-24
11,1e72c6fbe2714417ab74148322ef0b3a,Bay Area 511 BART Schedule,2023-05-25,2023-07-20
12,51dec30d7cc70349cf181ee3883f16d3,Bay Area 511 BART Schedule,2023-07-21,2023-09-08
13,601bb8208096363dec33e8c7227a9fd7,Bay Area 511 BART Schedule,2023-09-09,2023-09-11
14,f0e1a0efc1ff4b6b4db50c1a6ba38daf,Bay Area 511 BART Schedule,2023-09-12,2023-09-14
15,2556b89d71b4cf5806b80ae2ec0d1982,Bay Area 511 BART Schedule,2023-09-15,2023-09-28
16,c861c06fc34eef130338231df986d35e,Bay Area 511 BART Schedule,2023-09-29,2023-10-23
17,3adea49ae77bc1f15f8465eb93afd814,Bay Area 511 BART Schedule,2023-10-24,2023-11-28
18,c86c1dc2f0d5d791f70fc6fc7179e25d,Bay Area 511 BART Schedule,2023-11-29,2023-12-12
19,d9ce377350ee058b5c02d7f499bb968b,Bay Area 511 BART Schedule,2023-12-13,2023-12-15
20,fc3337fe050879d4f79fcceb93f0c45d,Bay Area 511 BART Schedule,2023-12-16,2023-12-29
21,1faa36f77cf7d8a19671409f29c9f16d,Bay Area 511 BART Schedule,2023-12-30,2024-01-01
22,02726ac5435af0a33fbac655b7d8d232,Bay Area 511 BART Schedule,2024-01-02,2024-01-05
23,f50113d666d27573c8b99721a7ec5d9d,Bay Area 511 BART Schedule,2024-01-06,2024-01-18
24,e7c2447eb0b26f89619620788754ba87,Bay Area 511 BART Schedule,2024-01-19,2024-01-29
25,377af3a93a57d3857010f7099940dfaf,Bay Area 511 BART Schedule,2024-01-30,2024-02-09
26,85015ab78d540fe405e14b3f9628cffe,Bay Area 511 BART Schedule,2024-02-10,2024-02-10
27,2a8780032b4f123a0e4c40dfda5a9c4a,Bay Area 511 BART Schedule,2024-02-11,2024-02-12
28,8dc55a4a9d5c0e79e1340c00aec39091,Bay Area 511 BART Schedule,2024-02-13,2024-02-29
29,a355c6a224632071cd99f9d9679ac25d,Bay Area 511 BART Schedule,2024-03-01,2024-04-12
30,3e22f1090d0d12096ee943c621298225,Bay Area 511 BART Schedule,2024-04-13,2024-05-29
31,70966c32d283c578aaa846caf502ab2b,Bay Area 511 BART Schedule,2024-05-30,2024-06-06
32,eabca4a910e48d87e8a86c4af3738ede,Bay Area 511 BART Schedule,2024-06-07,2024-06-16
33,b2d2ec1873d6e2a89c3d12e099d1a566,Bay Area 511 BART Schedule,2024-06-17,2024-07-08
34,3792919fdf9b491a5aeb5d55b6d61873,Bay Area 511 BART Schedule,2024-07-09,2024-08-05
35,3a98ea61036d107b63e8288965f8479a,Bay Area 511 BART Schedule,2024-08-06,2024-08-09
36,4aa4fca86f3576d3fd40958d162f7786,Bay Area 511 BART Schedule,2024-08-10,2024-08-12
37,19dcad91eb3e99e50cb254eedd4133b8,Bay Area 511 BART Schedule,2024-08-13,2024-08-13
38,8c3ed7154d8951bc164e0aee7cba915f,Bay Area 511 BART Schedule,2024-08-14,2024-09-11
39,ffd535d03c203cf59162dc35497b85d9,Bay Area 511 BART Schedule,2024-09-12,2024-10-11
66,91e60f85bf74c9be21b9db532d06b118,Bay Area 511 BART Schedule,2025-08-12,2025-10-19
67,6cec6766c6f903afdd904f1752d80b26,Bay Area 511 BART Schedule,2025-10-20,2025-10-24
68,67e36e5516e6f85ac558241bd9a5d3ba,Bay Area 511 BART Schedule,2025-10-25,2025-11-20
69,2c9434a95573df581e88541ec1bd5e73,Bay Area 511 BART Schedule,2025-11-21,2025-12-16
70,faa73c7e3c4280b96bb74237f422ed4b,Bay Area 511 BART Schedule,2025-12-17,2025-12-17
71,baac42d0428a57519afca1a5555334b5,Bay Area 511 BART Schedule,2025-12-18,2025-12-31
72,b4dda97100acf38a587f7f0fb447f6a9,Bay Area 511 BART Schedule,2026-01-01,2026-01-02
73,4d1c677d47f3c48a4323f506927383d3,Bay Area 511 BART Schedule,2026-01-03,2026-03-31
74,1aa4230f065e18b82c78ae8b0aabaf19,Bay Area 511 BART Schedule,2026-04-01,2026-04-23
75,bfb2078783000a9e17d3bdeb0a281f4f,Bay Area 511 BART Schedule,2026-04-24,2026-05-27
76,3d1e24aeee75adb17662d9d8cb2ec350,Bay Area 511 BART Schedule,2026-05-28,2026-05-28